---
version: '3'
services:
  solr:
    image: arclight/solr
    build:
      context: .
      dockerfile: Dockerfile.solr
    ports:
     - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - arclight
      - /opt/solr/arclight/solr/conf
