---
version: '2'
services:
  solr:
    image: arclight/solr
    build: .
    ports:
     - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - arclight
      - /opt/solr/arclight/solr/conf
